Rule =  [  unconditionally then Consequent
		|  for any Class [ DynamicReference ]] if Expression then Consequent 
		|  when Expression then Consequent
		|  whenever Expression then Consequent
		|  initially Rule.