# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: k2user
      MONGO_INITDB_ROOT_PASSWORD: SOh3TbYhx8ypJPxmt1oOfL

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: k2user
      ME_CONFIG_MONGODB_ADMINPASSWORD: SOh3TbYhx8ypJPxmt1oOfL
      ME_CONFIG_MONGODB_URL: mongodb://k2user:SOh3TbYhx8ypJPxmt1oOfL@mongo:27017/

  app-back:
    depends_on:
      - mongo
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: .
      target: k2-image
