# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: k2user
      MONGO_INITDB_ROOT_PASSWORD: SOh3TbYhx8ypJPxmt1oOfL
    networks:
      - k2net
  app-back:
    depends_on:
      - mongo
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: .
      target: k2-image
      network: k2net
networks:
  k2net:

