title = "K2 System KnowledgeBase"
wellcome = "Bem-vindo ao K2!"
datainput = "Entrada de dados"
wellcome2 = "O que vamos fazer hoje?"
workspace= "Área de trabalho"
alert = "Alertas"
register = "Por favor, se registre para acessar o K2!"
already = "Já tem uma conta? Conecte-se!"
forgot= "Esqueceu sua senha?"
